apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-devops
  template:
    metadata:
      labels:
        app: mini-devops
    spec:
      containers:
      - name: mini-devops
        image: tesseris/mini-devops-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000