apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-devops
  template:
    metadata:
      labels:
        app: mini-devops
    spec:

      containers:
      - name: mini-devops-container
        image: mini-devops-app
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
